name = "FjordSim"
uuid = "70d6b63c-c5d4-46ce-8d1e-8766361373eb"
version = "0.0.1"
authors = ["sia <yakubov.sha@gmail.com> and contributors"]

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
ClimaOcean = "0376089a-ecfe-4b0e-a64f-9c555d74d754"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
OceanBioME = "a49af516-9db8-4be4-be45-1dad61c5a376"
Oceananigans = "9e8cae18-63c1-5223-a75c-80ca9d6e9a09"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SeawaterPolynomials = "d496a93d-167e-4197-9f49-d3af4ff8fe40"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[weakdeps]
Thermodynamics = "b60c26fb-14c3-4610-9d3e-2d17fe7ff00c"

[compat]
Adapt = "4"
ClimaOcean = "0.8"
Dates = "1.10"
JLD2 = "0.6.2"
NCDatasets = "0.14.9"
OceanBioME = "0.16"
Oceananigans = "0.102, 0.103, 0.104"
Printf = "1.10"
SeawaterPolynomials = "0.3"
Statistics = "1.10"
Thermodynamics = "0.14"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
